[user]
name = "jj-ts tests"
email = "jj-ts-tests@example.com"

[revset-aliases]
'unpushable(to)' = '::to & mutable() & (description(exact:"") | (empty() & ~merges()))'
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()) & ~(unpushable(to)::))'
'bookmark_heads_in_stack(rev)' = 'trunk()..((trunk()..rev)::) & (bookmarks() | remote_bookmarks()) & ~(((trunk()..((trunk()..rev)::)) & mutable() & (description(exact:"") | (empty() & ~merges())))::)'
